using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Threading.Tasks.Dataflow;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TestsGeneratorLibrary
{
    public class TestsGenerator
    {
        public static async Task<TestClass> GenerateTest(string file)
        {
            SyntaxTree tree = CSharpSyntaxTree.ParseText(file);
            TestClass test = new TestClass();
            test.Name = "Test" + tree.FilePath.Substring(tree.FilePath.LastIndexOf("\\") + 1);
            CancellationToken token = new CancellationToken(false);

            var classes = tree.GetRoot().DescendantNodes().Where(n => n.IsKind(SyntaxKind.ClassDeclaration));
            var methods = classes.SelectMany(n => n.DescendantNodes().Where(node => node.IsKind(SyntaxKind.MethodDeclaration)));
            methods = methods.Where(m => m.ChildTokens().Any(t => t.IsKind(SyntaxKind.PublicKeyword)));

            test.Text = "using System;\r\n";
            test.Text += "namespace MyCode.Tests\r\n";
            test.Text += "{\r\n";
            test.Text += "\t[TestClass]\r\n";
            test.Text += "\tpublic class " + test.Name.Substring(0, test.Name.IndexOf(".")) + "\r\n";
            test.Text += "\t{\r\n";

            var methodBlock = new TransformBlock<SyntaxNode, string>(method => {
                string testMethod;
                testMethod = "\r\n";
                testMethod += "\t\t[TestMethod]\r\n";
                testMethod += "\t\t\tpublic void " + (method as MethodDeclarationSyntax).Identifier + "Test()\r\n";
                testMethod += "\t\t\t{\r\n";
                testMethod += "\t\t\t\tAssert.Fail(\"autogenerated\");\r\n";
                testMethod += "\t\t\t}\r\n";
                return testMethod;
            }, new ExecutionDataflowBlockOptions() { MaxDegreeOfParallelism = 2});

            foreach (var method in methods)
            {
                await methodBlock.SendAsync(method);
            }

            methodBlock.Complete();

            foreach (var method in methods)
            {
                test.Text += await methodBlock.ReceiveAsync();
            }

            test.Text += "\t}\r\n";
            test.Text += "}";
            return test;
        }
    }
}
